/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pro.guitest.main;


/**
 *
 * @author Aleksi Salminen
 */
public class TestForm extends javax.swing.JFrame {

    /**
     * Creates new form TestForm
     */
    public TestForm() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GasButtonGroup1 = new javax.swing.ButtonGroup();
        MainPane = new javax.swing.JTabbedPane();
        RealTimePanel = new javax.swing.JPanel();
        FilesPanel = new javax.swing.JPanel();
        SaveButton = new javax.swing.JButton();
        LoadButton = new javax.swing.JButton();
        ValuesPanel = new javax.swing.JPanel();
        MinimumLabel = new javax.swing.JLabel();
        MaximumLabel = new javax.swing.JLabel();
        AverageLabel = new javax.swing.JLabel();
        StationsPanel = new javax.swing.JPanel();
        StationsLabel = new javax.swing.JLabel();
        HelsinkiCheckBox = new javax.swing.JCheckBox();
        OuluCheckBox = new javax.swing.JCheckBox();
        KumpulaCheckBox = new javax.swing.JCheckBox();
        HelsinkiColorButton = new javax.swing.JButton();
        OuluColorButton = new javax.swing.JButton();
        KumpulaColorButton = new javax.swing.JButton();
        GasPanel = new javax.swing.JPanel();
        GasLabel = new javax.swing.JLabel();
        CO2RadioButton = new javax.swing.JRadioButton();
        SO2RadioButton = new javax.swing.JRadioButton();
        NOxRadioButton = new javax.swing.JRadioButton();
        TimePanel = new javax.swing.JPanel();
        TimeRangeLabel = new javax.swing.JLabel();
        TimeRangeDDList = new javax.swing.JComboBox<>();
        GraphPanel = new javax.swing.JPanel();
        GraphImage = new javax.swing.JLabel();
        HistoryPanel = new javax.swing.JPanel();
        FilesPanel2 = new javax.swing.JPanel();
        SaveButton2 = new javax.swing.JButton();
        LoadButton2 = new javax.swing.JButton();
        TimeRangePanel = new javax.swing.JPanel();
        TimeLabel = new javax.swing.JLabel();
        TimeStartDDList = new javax.swing.JComboBox<>();
        TimeStartLabel = new javax.swing.JLabel();
        TimeEndDDList = new javax.swing.JComboBox<>();
        TimeEndLabel = new javax.swing.JLabel();
        DatasetsPanel = new javax.swing.JPanel();
        DatasetsLabel = new javax.swing.JLabel();
        CO2ColorButton = new javax.swing.JButton();
        CO2IntensityColorButton = new javax.swing.JButton();
        CO2IndexedColorButton = new javax.swing.JButton();
        CO2IntensityIndexedColorButton = new javax.swing.JButton();
        CO2CheckBox = new javax.swing.JCheckBox();
        CO2IntensityCheckBox = new javax.swing.JCheckBox();
        CO2IndexedCheckBox = new javax.swing.JCheckBox();
        CO2IntensityIndexedCheckBox = new javax.swing.JCheckBox();
        GraphPanel2 = new javax.swing.JPanel();
        STATFIGraph1 = new javax.swing.JLabel();
        ComparisonPanel = new javax.swing.JPanel();
        FilesPanel3 = new javax.swing.JPanel();
        SaveButton3 = new javax.swing.JButton();
        LoadButton3 = new javax.swing.JButton();
        HistoryPanel2 = new javax.swing.JPanel();
        HistoryLabel = new javax.swing.JLabel();
        TimeRangePanel1 = new javax.swing.JPanel();
        TimeLabel1 = new javax.swing.JLabel();
        TimeStartDDList1 = new javax.swing.JComboBox<>();
        TimeStartLabel1 = new javax.swing.JLabel();
        TimeEndDDList1 = new javax.swing.JComboBox<>();
        TimeEndLabel1 = new javax.swing.JLabel();
        DatasetsPanel1 = new javax.swing.JPanel();
        DatasetsLabel1 = new javax.swing.JLabel();
        CO2ColorButton1 = new javax.swing.JButton();
        CO2IntensityColorButton1 = new javax.swing.JButton();
        CO2IndexedColorButton1 = new javax.swing.JButton();
        CO2IntensityIndexedColorButton1 = new javax.swing.JButton();
        CO2CheckBox1 = new javax.swing.JCheckBox();
        CO2IntensityCheckBox1 = new javax.swing.JCheckBox();
        CO2IndexedCheckBox1 = new javax.swing.JCheckBox();
        CO2IntensityIndexedCheckBox1 = new javax.swing.JCheckBox();
        GraphPanel3 = new javax.swing.JPanel();
        STATFIGraph2 = new javax.swing.JLabel();
        RealTimeSettingsPanel = new javax.swing.JPanel();
        RealTimeLabel = new javax.swing.JLabel();
        StationsPanel1 = new javax.swing.JPanel();
        StationsLabel1 = new javax.swing.JLabel();
        HelsinkiCheckBox1 = new javax.swing.JCheckBox();
        OuluCheckBox1 = new javax.swing.JCheckBox();
        KumpulaCheckBox1 = new javax.swing.JCheckBox();
        HelsinkiColorButton1 = new javax.swing.JButton();
        OuluColorButton1 = new javax.swing.JButton();
        KumpulaColorButton1 = new javax.swing.JButton();
        TimePanel1 = new javax.swing.JPanel();
        TimeRangeLabel1 = new javax.swing.JLabel();
        TimeRangeDDList1 = new javax.swing.JComboBox<>();
        RealTimeGraphsPanel = new javax.swing.JPanel();
        CO2Panel = new javax.swing.JPanel();
        CO2Label = new javax.swing.JLabel();
        CO2Graph = new javax.swing.JLabel();
        SO2Panel = new javax.swing.JPanel();
        SO2Label = new javax.swing.JLabel();
        CO2Graph1 = new javax.swing.JLabel();
        NOxPanel = new javax.swing.JPanel();
        NOxLabel = new javax.swing.JLabel();
        CO2Graph2 = new javax.swing.JLabel();
        AveragesPanel = new javax.swing.JPanel();
        FilesPanel4 = new javax.swing.JPanel();
        SaveButton4 = new javax.swing.JButton();
        LoadButton4 = new javax.swing.JButton();
        TimeRangePanel2 = new javax.swing.JPanel();
        TimeLabel2 = new javax.swing.JLabel();
        TimeStartDDList2 = new javax.swing.JComboBox<>();
        TimeStartLabel2 = new javax.swing.JLabel();
        TimeEndDDList2 = new javax.swing.JComboBox<>();
        TimeEndLabel2 = new javax.swing.JLabel();
        DatasetsPanel2 = new javax.swing.JPanel();
        DatasetsLabel2 = new javax.swing.JLabel();
        CO2ColorButton2 = new javax.swing.JButton();
        CO2IntensityColorButton2 = new javax.swing.JButton();
        CO2IndexedColorButton2 = new javax.swing.JButton();
        CO2IntensityIndexedColorButton2 = new javax.swing.JButton();
        CO2CheckBox2 = new javax.swing.JCheckBox();
        CO2IntensityCheckBox2 = new javax.swing.JCheckBox();
        CO2IndexedCheckBox2 = new javax.swing.JCheckBox();
        CO2IntensityIndexedCheckBox2 = new javax.swing.JCheckBox();
        StatfiGraphPanel = new javax.swing.JPanel();
        STATFILabel = new javax.swing.JLabel();
        STATFIGraph3 = new javax.swing.JLabel();
        SmearGraphPanel = new javax.swing.JPanel();
        SMEARLabel = new javax.swing.JLabel();
        SMEARGraph3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SaveButton.setText("Save");

        LoadButton.setText("Load");

        javax.swing.GroupLayout FilesPanelLayout = new javax.swing.GroupLayout(FilesPanel);
        FilesPanel.setLayout(FilesPanelLayout);
        FilesPanelLayout.setHorizontalGroup(
            FilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FilesPanelLayout.setVerticalGroup(
            FilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilesPanelLayout.createSequentialGroup()
                .addGroup(FilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(LoadButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MinimumLabel.setText("Minimum: 417");

        MaximumLabel.setText("Maximum: 458");

        AverageLabel.setText("Average: 430");

        javax.swing.GroupLayout ValuesPanelLayout = new javax.swing.GroupLayout(ValuesPanel);
        ValuesPanel.setLayout(ValuesPanelLayout);
        ValuesPanelLayout.setHorizontalGroup(
            ValuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ValuesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MinimumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MaximumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AverageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ValuesPanelLayout.setVerticalGroup(
            ValuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ValuesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ValuesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinimumLabel)
                    .addComponent(MaximumLabel)
                    .addComponent(AverageLabel))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        StationsLabel.setText("Monitoring stations");

        HelsinkiCheckBox.setText("Helsinki");
        HelsinkiCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelsinkiCheckBoxActionPerformed(evt);
            }
        });

        OuluCheckBox.setText("Oulu");
        OuluCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OuluCheckBoxActionPerformed(evt);
            }
        });

        KumpulaCheckBox.setText("Kumpula");

        HelsinkiColorButton.setBackground(new java.awt.Color(255, 0, 0));

        OuluColorButton.setBackground(new java.awt.Color(0, 153, 0));

        KumpulaColorButton.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout StationsPanelLayout = new javax.swing.GroupLayout(StationsPanel);
        StationsPanel.setLayout(StationsPanelLayout);
        StationsPanelLayout.setHorizontalGroup(
            StationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StationsPanelLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(StationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(KumpulaColorButton)
                    .addComponent(OuluColorButton)
                    .addComponent(HelsinkiColorButton))
                .addGap(31, 31, 31))
            .addGroup(StationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(StationsPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(StationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(StationsLabel)
                        .addComponent(KumpulaCheckBox)
                        .addGroup(StationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(OuluCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(HelsinkiCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap(36, Short.MAX_VALUE)))
        );
        StationsPanelLayout.setVerticalGroup(
            StationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StationsPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(HelsinkiColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OuluColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KumpulaColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(StationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(StationsPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(StationsLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(HelsinkiCheckBox)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(OuluCheckBox)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(KumpulaCheckBox)
                    .addContainerGap(11, Short.MAX_VALUE)))
        );

        GasLabel.setText("Selected gas");

        GasButtonGroup1.add(CO2RadioButton);
        CO2RadioButton.setText("CO2");

        GasButtonGroup1.add(SO2RadioButton);
        SO2RadioButton.setText("SO2");

        GasButtonGroup1.add(NOxRadioButton);
        NOxRadioButton.setText("NOx");

        javax.swing.GroupLayout GasPanelLayout = new javax.swing.GroupLayout(GasPanel);
        GasPanel.setLayout(GasPanelLayout);
        GasPanelLayout.setHorizontalGroup(
            GasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
            .addGroup(GasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(GasPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(GasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(GasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CO2RadioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GasLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(GasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(NOxRadioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(SO2RadioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)))
                    .addContainerGap(66, Short.MAX_VALUE)))
        );
        GasPanelLayout.setVerticalGroup(
            GasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(GasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(GasPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(GasLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(CO2RadioButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(SO2RadioButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(NOxRadioButton)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        TimeRangeLabel.setText("Time range");

        TimeRangeDDList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 day", "2 days", "1 week", "1 month" }));
        TimeRangeDDList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeRangeDDListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TimePanelLayout = new javax.swing.GroupLayout(TimePanel);
        TimePanel.setLayout(TimePanelLayout);
        TimePanelLayout.setHorizontalGroup(
            TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TimeRangeLabel)
                    .addComponent(TimeRangeDDList, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        TimePanelLayout.setVerticalGroup(
            TimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TimeRangeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimeRangeDDList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GraphPanel.setBackground(new java.awt.Color(51, 51, 51));

        GraphImage.setIcon(new javax.swing.ImageIcon("./src/main/java/images/GraphSMEAR.png"));
        GraphImage.setMaximumSize(new java.awt.Dimension(300, 200));
        GraphImage.setMinimumSize(new java.awt.Dimension(300, 200));
        GraphImage.setPreferredSize(new java.awt.Dimension(300, 200));

        javax.swing.GroupLayout GraphPanelLayout = new javax.swing.GroupLayout(GraphPanel);
        GraphPanel.setLayout(GraphPanelLayout);
        GraphPanelLayout.setHorizontalGroup(
            GraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GraphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GraphImage, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addContainerGap())
        );
        GraphPanelLayout.setVerticalGroup(
            GraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GraphPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GraphImage, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout RealTimePanelLayout = new javax.swing.GroupLayout(RealTimePanel);
        RealTimePanel.setLayout(RealTimePanelLayout);
        RealTimePanelLayout.setHorizontalGroup(
            RealTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RealTimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RealTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FilesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StationsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(RealTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RealTimePanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(ValuesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RealTimePanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(GraphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RealTimePanelLayout.setVerticalGroup(
            RealTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RealTimePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RealTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FilesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValuesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RealTimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(RealTimePanelLayout.createSequentialGroup()
                        .addComponent(StationsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPane.addTab("Real-time", RealTimePanel);

        SaveButton2.setText("Save");

        LoadButton2.setText("Load");

        javax.swing.GroupLayout FilesPanel2Layout = new javax.swing.GroupLayout(FilesPanel2);
        FilesPanel2.setLayout(FilesPanel2Layout);
        FilesPanel2Layout.setHorizontalGroup(
            FilesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilesPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SaveButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoadButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FilesPanel2Layout.setVerticalGroup(
            FilesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilesPanel2Layout.createSequentialGroup()
                .addGroup(FilesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton2)
                    .addComponent(LoadButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TimeLabel.setText("Time Range");

        TimeStartDDList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021" }));

        TimeStartLabel.setText("Start:");

        TimeEndDDList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021" }));

        TimeEndLabel.setText("End:");

        javax.swing.GroupLayout TimeRangePanelLayout = new javax.swing.GroupLayout(TimeRangePanel);
        TimeRangePanel.setLayout(TimeRangePanelLayout);
        TimeRangePanelLayout.setHorizontalGroup(
            TimeRangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimeRangePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TimeRangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TimeRangePanelLayout.createSequentialGroup()
                        .addComponent(TimeEndLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TimeEndDDList, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TimeRangePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(TimeRangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TimeLabel)
                            .addGroup(TimeRangePanelLayout.createSequentialGroup()
                                .addComponent(TimeStartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TimeStartDDList, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(105, 105, 105))
        );
        TimeRangePanelLayout.setVerticalGroup(
            TimeRangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimeRangePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TimeRangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeStartDDList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeStartLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TimeRangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeEndLabel)
                    .addComponent(TimeEndDDList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        DatasetsLabel.setText("Datasets");

        CO2ColorButton.setBackground(new java.awt.Color(255, 0, 0));

        CO2IntensityColorButton.setBackground(new java.awt.Color(0, 153, 0));

        CO2IndexedColorButton.setBackground(new java.awt.Color(0, 0, 204));

        CO2IntensityIndexedColorButton.setBackground(new java.awt.Color(102, 0, 102));

        CO2CheckBox.setText("CO2 (tonnes)");

        CO2IntensityCheckBox.setText("CO2 intensity");

        CO2IndexedCheckBox.setText("CO2 (indexed)");

        CO2IntensityIndexedCheckBox.setText("CO2 intensity (indexed)");

        javax.swing.GroupLayout DatasetsPanelLayout = new javax.swing.GroupLayout(DatasetsPanel);
        DatasetsPanel.setLayout(DatasetsPanelLayout);
        DatasetsPanelLayout.setHorizontalGroup(
            DatasetsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatasetsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatasetsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatasetsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(DatasetsLabel)
                        .addGroup(DatasetsPanelLayout.createSequentialGroup()
                            .addComponent(CO2ColorButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CO2CheckBox))
                        .addGroup(DatasetsPanelLayout.createSequentialGroup()
                            .addComponent(CO2IntensityColorButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CO2IntensityCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(DatasetsPanelLayout.createSequentialGroup()
                            .addComponent(CO2IndexedColorButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CO2IndexedCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(DatasetsPanelLayout.createSequentialGroup()
                        .addComponent(CO2IntensityIndexedColorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CO2IntensityIndexedCheckBox)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        DatasetsPanelLayout.setVerticalGroup(
            DatasetsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatasetsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatasetsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DatasetsPanelLayout.createSequentialGroup()
                        .addGroup(DatasetsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DatasetsPanelLayout.createSequentialGroup()
                                .addGroup(DatasetsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(DatasetsPanelLayout.createSequentialGroup()
                                        .addComponent(DatasetsLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CO2ColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CO2CheckBox))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CO2IntensityColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CO2IntensityCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CO2IndexedColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CO2IndexedCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatasetsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CO2IntensityIndexedColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CO2IntensityIndexedCheckBox))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        GraphPanel2.setBackground(new java.awt.Color(51, 51, 51));

        STATFIGraph1.setIcon(new javax.swing.ImageIcon("./src/main/java/images/GraphSTATFI.png"));
        STATFIGraph1.setText("jLabel1");

        javax.swing.GroupLayout GraphPanel2Layout = new javax.swing.GroupLayout(GraphPanel2);
        GraphPanel2.setLayout(GraphPanel2Layout);
        GraphPanel2Layout.setHorizontalGroup(
            GraphPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GraphPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(STATFIGraph1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GraphPanel2Layout.setVerticalGroup(
            GraphPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GraphPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(STATFIGraph1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout HistoryPanelLayout = new javax.swing.GroupLayout(HistoryPanel);
        HistoryPanel.setLayout(HistoryPanelLayout);
        HistoryPanelLayout.setHorizontalGroup(
            HistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FilesPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatasetsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeRangePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(GraphPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        HistoryPanelLayout.setVerticalGroup(
            HistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(HistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HistoryPanelLayout.createSequentialGroup()
                        .addComponent(FilesPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TimeRangePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DatasetsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GraphPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPane.addTab("History", HistoryPanel);

        SaveButton3.setText("Save");

        LoadButton3.setText("Load");

        javax.swing.GroupLayout FilesPanel3Layout = new javax.swing.GroupLayout(FilesPanel3);
        FilesPanel3.setLayout(FilesPanel3Layout);
        FilesPanel3Layout.setHorizontalGroup(
            FilesPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilesPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SaveButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoadButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FilesPanel3Layout.setVerticalGroup(
            FilesPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilesPanel3Layout.createSequentialGroup()
                .addGroup(FilesPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton3)
                    .addComponent(LoadButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        HistoryPanel2.setBackground(new java.awt.Color(211, 213, 197));

        HistoryLabel.setText("HISTORICAL VALUES");

        TimeRangePanel1.setBackground(new java.awt.Color(211, 213, 197));

        TimeLabel1.setText("Time Range");

        TimeStartDDList1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021" }));

        TimeStartLabel1.setText("Start:");

        TimeEndDDList1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021" }));

        TimeEndLabel1.setText("End:");

        javax.swing.GroupLayout TimeRangePanel1Layout = new javax.swing.GroupLayout(TimeRangePanel1);
        TimeRangePanel1.setLayout(TimeRangePanel1Layout);
        TimeRangePanel1Layout.setHorizontalGroup(
            TimeRangePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimeRangePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TimeRangePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimeRangePanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(TimeRangePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TimeLabel1)
                            .addGroup(TimeRangePanel1Layout.createSequentialGroup()
                                .addComponent(TimeStartLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TimeStartDDList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(118, 118, 118))
                    .addGroup(TimeRangePanel1Layout.createSequentialGroup()
                        .addComponent(TimeEndLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TimeEndDDList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        TimeRangePanel1Layout.setVerticalGroup(
            TimeRangePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimeRangePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TimeLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TimeRangePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeStartDDList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeStartLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TimeRangePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeEndLabel1)
                    .addComponent(TimeEndDDList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        DatasetsPanel1.setBackground(new java.awt.Color(211, 213, 197));

        DatasetsLabel1.setText("Datasets");

        CO2ColorButton1.setBackground(new java.awt.Color(255, 0, 0));

        CO2IntensityColorButton1.setBackground(new java.awt.Color(0, 153, 0));

        CO2IndexedColorButton1.setBackground(new java.awt.Color(0, 0, 204));

        CO2IntensityIndexedColorButton1.setBackground(new java.awt.Color(102, 0, 102));

        CO2CheckBox1.setText("CO2 (tonnes)");

        CO2IntensityCheckBox1.setText("CO2 intensity");

        CO2IndexedCheckBox1.setText("CO2 (indexed)");

        CO2IntensityIndexedCheckBox1.setFont(new java.awt.Font("sansserif", 0, 8)); // NOI18N
        CO2IntensityIndexedCheckBox1.setText("CO2 intensity (indexed)");

        javax.swing.GroupLayout DatasetsPanel1Layout = new javax.swing.GroupLayout(DatasetsPanel1);
        DatasetsPanel1.setLayout(DatasetsPanel1Layout);
        DatasetsPanel1Layout.setHorizontalGroup(
            DatasetsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatasetsPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DatasetsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatasetsPanel1Layout.createSequentialGroup()
                        .addGroup(DatasetsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CO2IntensityIndexedColorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CO2IndexedColorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DatasetsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CO2IntensityIndexedCheckBox1)
                            .addComponent(CO2IndexedCheckBox1))
                        .addGap(58, 58, 58))
                    .addGroup(DatasetsPanel1Layout.createSequentialGroup()
                        .addGroup(DatasetsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DatasetsLabel1)
                            .addGroup(DatasetsPanel1Layout.createSequentialGroup()
                                .addGroup(DatasetsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(CO2ColorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(CO2IntensityColorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DatasetsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CO2CheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CO2IntensityCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(38, 38, 38))))
        );
        DatasetsPanel1Layout.setVerticalGroup(
            DatasetsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatasetsPanel1Layout.createSequentialGroup()
                .addComponent(DatasetsLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatasetsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DatasetsPanel1Layout.createSequentialGroup()
                        .addGroup(DatasetsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CO2ColorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CO2CheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CO2IntensityColorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CO2IntensityCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatasetsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CO2IndexedColorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CO2IndexedCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatasetsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CO2IntensityIndexedColorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CO2IntensityIndexedCheckBox1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GraphPanel3.setBackground(new java.awt.Color(51, 51, 51));

        STATFIGraph2.setIcon(new javax.swing.ImageIcon("./src/main/java/images/GraphSTATFI3.png"));

        javax.swing.GroupLayout GraphPanel3Layout = new javax.swing.GroupLayout(GraphPanel3);
        GraphPanel3.setLayout(GraphPanel3Layout);
        GraphPanel3Layout.setHorizontalGroup(
            GraphPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GraphPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(STATFIGraph2, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        GraphPanel3Layout.setVerticalGroup(
            GraphPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GraphPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(STATFIGraph2, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout HistoryPanel2Layout = new javax.swing.GroupLayout(HistoryPanel2);
        HistoryPanel2.setLayout(HistoryPanel2Layout);
        HistoryPanel2Layout.setHorizontalGroup(
            HistoryPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryPanel2Layout.createSequentialGroup()
                .addGroup(HistoryPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HistoryPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(HistoryLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(HistoryPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TimeRangePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DatasetsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(GraphPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        HistoryPanel2Layout.setVerticalGroup(
            HistoryPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(HistoryLabel)
                .addGap(18, 18, 18)
                .addGroup(HistoryPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GraphPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DatasetsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TimeRangePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        RealTimeSettingsPanel.setBackground(new java.awt.Color(185, 184, 204));

        RealTimeLabel.setText("REAL-TIME DATA");

        StationsPanel1.setBackground(new java.awt.Color(185, 184, 204));

        StationsLabel1.setText("Monitoring stations");

        HelsinkiCheckBox1.setText("Helsinki");
        HelsinkiCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelsinkiCheckBox1ActionPerformed(evt);
            }
        });

        OuluCheckBox1.setText("Oulu");
        OuluCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OuluCheckBox1ActionPerformed(evt);
            }
        });

        KumpulaCheckBox1.setText("Kumpula");

        HelsinkiColorButton1.setBackground(new java.awt.Color(255, 0, 0));

        OuluColorButton1.setBackground(new java.awt.Color(0, 153, 0));

        KumpulaColorButton1.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout StationsPanel1Layout = new javax.swing.GroupLayout(StationsPanel1);
        StationsPanel1.setLayout(StationsPanel1Layout);
        StationsPanel1Layout.setHorizontalGroup(
            StationsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StationsPanel1Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(StationsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HelsinkiColorButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OuluColorButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(KumpulaColorButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(StationsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(StationsPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(StationsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(StationsLabel1)
                        .addComponent(KumpulaCheckBox1)
                        .addGroup(StationsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(OuluCheckBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HelsinkiCheckBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        StationsPanel1Layout.setVerticalGroup(
            StationsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StationsPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(HelsinkiColorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OuluColorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KumpulaColorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(StationsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(StationsPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(StationsLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(HelsinkiCheckBox1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(OuluCheckBox1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(KumpulaCheckBox1)
                    .addContainerGap(11, Short.MAX_VALUE)))
        );

        TimePanel1.setBackground(new java.awt.Color(185, 184, 204));

        TimeRangeLabel1.setText("Time range");

        TimeRangeDDList1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 day", "2 days", "1 week", "1 month" }));
        TimeRangeDDList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeRangeDDList1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TimePanel1Layout = new javax.swing.GroupLayout(TimePanel1);
        TimePanel1.setLayout(TimePanel1Layout);
        TimePanel1Layout.setHorizontalGroup(
            TimePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TimePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TimeRangeLabel1)
                    .addComponent(TimeRangeDDList1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        TimePanel1Layout.setVerticalGroup(
            TimePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimePanel1Layout.createSequentialGroup()
                .addComponent(TimeRangeLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimeRangeDDList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RealTimeSettingsPanelLayout = new javax.swing.GroupLayout(RealTimeSettingsPanel);
        RealTimeSettingsPanel.setLayout(RealTimeSettingsPanelLayout);
        RealTimeSettingsPanelLayout.setHorizontalGroup(
            RealTimeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RealTimeSettingsPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(RealTimeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StationsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RealTimeSettingsPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(RealTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RealTimeSettingsPanelLayout.setVerticalGroup(
            RealTimeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RealTimeSettingsPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(RealTimeLabel)
                .addGap(27, 27, 27)
                .addComponent(StationsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(TimePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        RealTimeGraphsPanel.setBackground(new java.awt.Color(185, 184, 204));

        CO2Panel.setBackground(new java.awt.Color(185, 184, 204));

        CO2Label.setText("CO2");

        CO2Graph.setIcon(new javax.swing.ImageIcon("./src/main/java/images/GraphSMEAR3.png"));

        javax.swing.GroupLayout CO2PanelLayout = new javax.swing.GroupLayout(CO2Panel);
        CO2Panel.setLayout(CO2PanelLayout);
        CO2PanelLayout.setHorizontalGroup(
            CO2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CO2PanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(CO2Label)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(CO2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CO2Graph, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        CO2PanelLayout.setVerticalGroup(
            CO2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CO2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CO2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CO2Graph)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SO2Panel.setBackground(new java.awt.Color(185, 184, 204));

        SO2Label.setText("SO2");

        CO2Graph1.setIcon(new javax.swing.ImageIcon("./src/main/java/images/GraphSMEAR3.png"));

        javax.swing.GroupLayout SO2PanelLayout = new javax.swing.GroupLayout(SO2Panel);
        SO2Panel.setLayout(SO2PanelLayout);
        SO2PanelLayout.setHorizontalGroup(
            SO2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SO2PanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(SO2Label)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(SO2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CO2Graph1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        SO2PanelLayout.setVerticalGroup(
            SO2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SO2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SO2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CO2Graph1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NOxPanel.setBackground(new java.awt.Color(185, 184, 204));

        NOxLabel.setText("NOx");

        CO2Graph2.setIcon(new javax.swing.ImageIcon("./src/main/java/images/GraphSMEAR3.png"));

        javax.swing.GroupLayout NOxPanelLayout = new javax.swing.GroupLayout(NOxPanel);
        NOxPanel.setLayout(NOxPanelLayout);
        NOxPanelLayout.setHorizontalGroup(
            NOxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NOxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CO2Graph2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(NOxPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(NOxLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NOxPanelLayout.setVerticalGroup(
            NOxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NOxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NOxLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CO2Graph2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RealTimeGraphsPanelLayout = new javax.swing.GroupLayout(RealTimeGraphsPanel);
        RealTimeGraphsPanel.setLayout(RealTimeGraphsPanelLayout);
        RealTimeGraphsPanelLayout.setHorizontalGroup(
            RealTimeGraphsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RealTimeGraphsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CO2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SO2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NOxPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        RealTimeGraphsPanelLayout.setVerticalGroup(
            RealTimeGraphsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RealTimeGraphsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RealTimeGraphsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CO2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SO2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NOxPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ComparisonPanelLayout = new javax.swing.GroupLayout(ComparisonPanel);
        ComparisonPanel.setLayout(ComparisonPanelLayout);
        ComparisonPanelLayout.setHorizontalGroup(
            ComparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComparisonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ComparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FilesPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RealTimeSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ComparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HistoryPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RealTimeGraphsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ComparisonPanelLayout.setVerticalGroup(
            ComparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComparisonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ComparisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ComparisonPanelLayout.createSequentialGroup()
                        .addComponent(HistoryPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RealTimeGraphsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ComparisonPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(FilesPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RealTimeSettingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPane.addTab("Comparison", ComparisonPanel);

        SaveButton4.setText("Save");

        LoadButton4.setText("Load");

        javax.swing.GroupLayout FilesPanel4Layout = new javax.swing.GroupLayout(FilesPanel4);
        FilesPanel4.setLayout(FilesPanel4Layout);
        FilesPanel4Layout.setHorizontalGroup(
            FilesPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilesPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SaveButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoadButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FilesPanel4Layout.setVerticalGroup(
            FilesPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilesPanel4Layout.createSequentialGroup()
                .addGroup(FilesPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton4)
                    .addComponent(LoadButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TimeLabel2.setText("Time Range");

        TimeStartDDList2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021" }));

        TimeStartLabel2.setText("Start:");

        TimeEndDDList2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021" }));

        TimeEndLabel2.setText("End:");

        javax.swing.GroupLayout TimeRangePanel2Layout = new javax.swing.GroupLayout(TimeRangePanel2);
        TimeRangePanel2.setLayout(TimeRangePanel2Layout);
        TimeRangePanel2Layout.setHorizontalGroup(
            TimeRangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimeRangePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TimeRangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TimeRangePanel2Layout.createSequentialGroup()
                        .addComponent(TimeEndLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TimeEndDDList2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TimeRangePanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(TimeRangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TimeLabel2)
                            .addGroup(TimeRangePanel2Layout.createSequentialGroup()
                                .addComponent(TimeStartLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TimeStartDDList2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(105, 105, 105))
        );
        TimeRangePanel2Layout.setVerticalGroup(
            TimeRangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimeRangePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TimeLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TimeRangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeStartDDList2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeStartLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TimeRangePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeEndLabel2)
                    .addComponent(TimeEndDDList2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        DatasetsLabel2.setText("Datasets");

        CO2ColorButton2.setBackground(new java.awt.Color(255, 0, 0));

        CO2IntensityColorButton2.setBackground(new java.awt.Color(0, 153, 0));

        CO2IndexedColorButton2.setBackground(new java.awt.Color(0, 0, 204));

        CO2IntensityIndexedColorButton2.setBackground(new java.awt.Color(102, 0, 102));

        CO2CheckBox2.setText("CO2 (tonnes)");

        CO2IntensityCheckBox2.setText("CO2 intensity");

        CO2IndexedCheckBox2.setText("CO2 (indexed)");

        CO2IntensityIndexedCheckBox2.setText("CO2 intensity (indexed)");

        javax.swing.GroupLayout DatasetsPanel2Layout = new javax.swing.GroupLayout(DatasetsPanel2);
        DatasetsPanel2.setLayout(DatasetsPanel2Layout);
        DatasetsPanel2Layout.setHorizontalGroup(
            DatasetsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatasetsPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatasetsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatasetsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(DatasetsLabel2)
                        .addGroup(DatasetsPanel2Layout.createSequentialGroup()
                            .addComponent(CO2ColorButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CO2CheckBox2))
                        .addGroup(DatasetsPanel2Layout.createSequentialGroup()
                            .addComponent(CO2IntensityColorButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CO2IntensityCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(DatasetsPanel2Layout.createSequentialGroup()
                            .addComponent(CO2IndexedColorButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CO2IndexedCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(DatasetsPanel2Layout.createSequentialGroup()
                        .addComponent(CO2IntensityIndexedColorButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CO2IntensityIndexedCheckBox2)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        DatasetsPanel2Layout.setVerticalGroup(
            DatasetsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatasetsPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatasetsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DatasetsPanel2Layout.createSequentialGroup()
                        .addGroup(DatasetsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DatasetsPanel2Layout.createSequentialGroup()
                                .addGroup(DatasetsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(DatasetsPanel2Layout.createSequentialGroup()
                                        .addComponent(DatasetsLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CO2ColorButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CO2CheckBox2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CO2IntensityColorButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CO2IntensityCheckBox2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CO2IndexedColorButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CO2IndexedCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatasetsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CO2IntensityIndexedColorButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CO2IntensityIndexedCheckBox2))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        StatfiGraphPanel.setBackground(new java.awt.Color(51, 51, 51));

        STATFILabel.setBackground(new java.awt.Color(204, 204, 204));
        STATFILabel.setText("STATFI");

        STATFIGraph3.setIcon(new javax.swing.ImageIcon("./src/main/java/images/GraphSTATFI2.png"));

        javax.swing.GroupLayout StatfiGraphPanelLayout = new javax.swing.GroupLayout(StatfiGraphPanel);
        StatfiGraphPanel.setLayout(StatfiGraphPanelLayout);
        StatfiGraphPanelLayout.setHorizontalGroup(
            StatfiGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatfiGraphPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(STATFIGraph3)
                .addContainerGap())
            .addGroup(StatfiGraphPanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(STATFILabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StatfiGraphPanelLayout.setVerticalGroup(
            StatfiGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatfiGraphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(STATFILabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(STATFIGraph3)
                .addContainerGap())
        );

        SmearGraphPanel.setBackground(new java.awt.Color(51, 51, 51));

        SMEARLabel.setText("SMEAR");

        SMEARGraph3.setIcon(new javax.swing.ImageIcon("./src/main/java/images/GraphSMEAR2.png"));

        javax.swing.GroupLayout SmearGraphPanelLayout = new javax.swing.GroupLayout(SmearGraphPanel);
        SmearGraphPanel.setLayout(SmearGraphPanelLayout);
        SmearGraphPanelLayout.setHorizontalGroup(
            SmearGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SmearGraphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SMEARGraph3, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(SmearGraphPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(SMEARLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SmearGraphPanelLayout.setVerticalGroup(
            SmearGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SmearGraphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SMEARLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SMEARGraph3)
                .addContainerGap())
        );

        javax.swing.GroupLayout AveragesPanelLayout = new javax.swing.GroupLayout(AveragesPanel);
        AveragesPanel.setLayout(AveragesPanelLayout);
        AveragesPanelLayout.setHorizontalGroup(
            AveragesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AveragesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FilesPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(TimeRangePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(DatasetsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(AveragesPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(StatfiGraphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(SmearGraphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AveragesPanelLayout.setVerticalGroup(
            AveragesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AveragesPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(AveragesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FilesPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatasetsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AveragesPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(TimeRangePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(AveragesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StatfiGraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SmearGraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPane.addTab("Averages", AveragesPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HelsinkiCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelsinkiCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HelsinkiCheckBoxActionPerformed

    private void OuluCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OuluCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OuluCheckBoxActionPerformed

    private void TimeRangeDDListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeRangeDDListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeRangeDDListActionPerformed

    private void HelsinkiCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelsinkiCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HelsinkiCheckBox1ActionPerformed

    private void OuluCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OuluCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OuluCheckBox1ActionPerformed

    private void TimeRangeDDList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeRangeDDList1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeRangeDDList1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AverageLabel;
    private javax.swing.JPanel AveragesPanel;
    private javax.swing.JCheckBox CO2CheckBox;
    private javax.swing.JCheckBox CO2CheckBox1;
    private javax.swing.JCheckBox CO2CheckBox2;
    private javax.swing.JButton CO2ColorButton;
    private javax.swing.JButton CO2ColorButton1;
    private javax.swing.JButton CO2ColorButton2;
    private javax.swing.JLabel CO2Graph;
    private javax.swing.JLabel CO2Graph1;
    private javax.swing.JLabel CO2Graph2;
    private javax.swing.JCheckBox CO2IndexedCheckBox;
    private javax.swing.JCheckBox CO2IndexedCheckBox1;
    private javax.swing.JCheckBox CO2IndexedCheckBox2;
    private javax.swing.JButton CO2IndexedColorButton;
    private javax.swing.JButton CO2IndexedColorButton1;
    private javax.swing.JButton CO2IndexedColorButton2;
    private javax.swing.JCheckBox CO2IntensityCheckBox;
    private javax.swing.JCheckBox CO2IntensityCheckBox1;
    private javax.swing.JCheckBox CO2IntensityCheckBox2;
    private javax.swing.JButton CO2IntensityColorButton;
    private javax.swing.JButton CO2IntensityColorButton1;
    private javax.swing.JButton CO2IntensityColorButton2;
    private javax.swing.JCheckBox CO2IntensityIndexedCheckBox;
    private javax.swing.JCheckBox CO2IntensityIndexedCheckBox1;
    private javax.swing.JCheckBox CO2IntensityIndexedCheckBox2;
    private javax.swing.JButton CO2IntensityIndexedColorButton;
    private javax.swing.JButton CO2IntensityIndexedColorButton1;
    private javax.swing.JButton CO2IntensityIndexedColorButton2;
    private javax.swing.JLabel CO2Label;
    private javax.swing.JPanel CO2Panel;
    private javax.swing.JRadioButton CO2RadioButton;
    private javax.swing.JPanel ComparisonPanel;
    private javax.swing.JLabel DatasetsLabel;
    private javax.swing.JLabel DatasetsLabel1;
    private javax.swing.JLabel DatasetsLabel2;
    private javax.swing.JPanel DatasetsPanel;
    private javax.swing.JPanel DatasetsPanel1;
    private javax.swing.JPanel DatasetsPanel2;
    private javax.swing.JPanel FilesPanel;
    private javax.swing.JPanel FilesPanel2;
    private javax.swing.JPanel FilesPanel3;
    private javax.swing.JPanel FilesPanel4;
    private javax.swing.ButtonGroup GasButtonGroup1;
    private javax.swing.JLabel GasLabel;
    private javax.swing.JPanel GasPanel;
    private javax.swing.JLabel GraphImage;
    private javax.swing.JPanel GraphPanel;
    private javax.swing.JPanel GraphPanel2;
    private javax.swing.JPanel GraphPanel3;
    private javax.swing.JCheckBox HelsinkiCheckBox;
    private javax.swing.JCheckBox HelsinkiCheckBox1;
    private javax.swing.JButton HelsinkiColorButton;
    private javax.swing.JButton HelsinkiColorButton1;
    private javax.swing.JLabel HistoryLabel;
    private javax.swing.JPanel HistoryPanel;
    private javax.swing.JPanel HistoryPanel2;
    private javax.swing.JCheckBox KumpulaCheckBox;
    private javax.swing.JCheckBox KumpulaCheckBox1;
    private javax.swing.JButton KumpulaColorButton;
    private javax.swing.JButton KumpulaColorButton1;
    private javax.swing.JButton LoadButton;
    private javax.swing.JButton LoadButton2;
    private javax.swing.JButton LoadButton3;
    private javax.swing.JButton LoadButton4;
    private javax.swing.JTabbedPane MainPane;
    private javax.swing.JLabel MaximumLabel;
    private javax.swing.JLabel MinimumLabel;
    private javax.swing.JLabel NOxLabel;
    private javax.swing.JPanel NOxPanel;
    private javax.swing.JRadioButton NOxRadioButton;
    private javax.swing.JCheckBox OuluCheckBox;
    private javax.swing.JCheckBox OuluCheckBox1;
    private javax.swing.JButton OuluColorButton;
    private javax.swing.JButton OuluColorButton1;
    private javax.swing.JPanel RealTimeGraphsPanel;
    private javax.swing.JLabel RealTimeLabel;
    private javax.swing.JPanel RealTimePanel;
    private javax.swing.JPanel RealTimeSettingsPanel;
    private javax.swing.JLabel SMEARGraph3;
    private javax.swing.JLabel SMEARLabel;
    private javax.swing.JLabel SO2Label;
    private javax.swing.JPanel SO2Panel;
    private javax.swing.JRadioButton SO2RadioButton;
    private javax.swing.JLabel STATFIGraph1;
    private javax.swing.JLabel STATFIGraph2;
    private javax.swing.JLabel STATFIGraph3;
    private javax.swing.JLabel STATFILabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton SaveButton2;
    private javax.swing.JButton SaveButton3;
    private javax.swing.JButton SaveButton4;
    private javax.swing.JPanel SmearGraphPanel;
    private javax.swing.JPanel StatfiGraphPanel;
    private javax.swing.JLabel StationsLabel;
    private javax.swing.JLabel StationsLabel1;
    private javax.swing.JPanel StationsPanel;
    private javax.swing.JPanel StationsPanel1;
    private javax.swing.JComboBox<String> TimeEndDDList;
    private javax.swing.JComboBox<String> TimeEndDDList1;
    private javax.swing.JComboBox<String> TimeEndDDList2;
    private javax.swing.JLabel TimeEndLabel;
    private javax.swing.JLabel TimeEndLabel1;
    private javax.swing.JLabel TimeEndLabel2;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JLabel TimeLabel1;
    private javax.swing.JLabel TimeLabel2;
    private javax.swing.JPanel TimePanel;
    private javax.swing.JPanel TimePanel1;
    private javax.swing.JComboBox<String> TimeRangeDDList;
    private javax.swing.JComboBox<String> TimeRangeDDList1;
    private javax.swing.JLabel TimeRangeLabel;
    private javax.swing.JLabel TimeRangeLabel1;
    private javax.swing.JPanel TimeRangePanel;
    private javax.swing.JPanel TimeRangePanel1;
    private javax.swing.JPanel TimeRangePanel2;
    private javax.swing.JComboBox<String> TimeStartDDList;
    private javax.swing.JComboBox<String> TimeStartDDList1;
    private javax.swing.JComboBox<String> TimeStartDDList2;
    private javax.swing.JLabel TimeStartLabel;
    private javax.swing.JLabel TimeStartLabel1;
    private javax.swing.JLabel TimeStartLabel2;
    private javax.swing.JPanel ValuesPanel;
    // End of variables declaration//GEN-END:variables
}
